name: childcontrols
description: "A parental control application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  local_auth: ^2.1.8
  flutter_background_service: ^5.0.5
  device_apps: ^2.2.0
  fl_chart: ^0.66.2
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 